// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

import 'package:tencent_rtc_sdk/bindings/manager/manager_struct.dart';
import 'package:tencent_rtc_sdk/bindings/trtc/trtc_cloud_struct.dart';

/// Bindings for `src/ffi_test.h`.
///
/// Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
///
class FFIBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FFIBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FFIBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int InitDartApiDL(ffi.Pointer<ffi.Void> data) {
    return _InitDartApiDL(data);
  }

  late final _InitDartApiDLPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'LiteavFFIInitApiDL');
  late final _InitDartApiDL =
      _InitDartApiDLPtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  int callApi(
    trtc_cloud trtcCloud,
  ) {
    return _callApi(
      trtcCloud,
    );
  }

  late final _callApiPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>('callApi');
  late final _callApi = _callApiPtr.asFunction<int Function(trtc_cloud)>();

  void registerListener(int sender_port, trtc_cloud trtcCloud) {
    _registerListener(sender_port, trtcCloud);
  }

  late final _registerListenerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, trtc_cloud)>>(
          'LiteavFFIRegisterTRTCCloudObserver');
  late final _registerListener =
      _registerListenerPtr.asFunction<void Function(int, trtc_cloud)>();

  void unRegisterListener(trtc_cloud trtcCloud) {
    _unRegisterListener(trtcCloud);
  }

  late final _unRegisterListenerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(trtc_cloud)>>(
          'LiteavFFIUnRegisterTRTCCloudObserver');
  late final _unRegisterListener =
      _unRegisterListenerPtr.asFunction<void Function(trtc_cloud)>();

  int registerLogObserver(int sender_port, ffi.Pointer<ffi.Void> instance) {
    return _registerLogObserver(sender_port, instance);
  }

  late final _registerLogObserverPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Void>)>>(
      'LiteavFFIRegisterLogObserver');
  late final _registerLogObserver = _registerLogObserverPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>)>();

  int unRegisterLogObserver(
    int sender_port,
    ffi.Pointer<ffi.Void> instance,
  ) {
    return _unRegisterLogObserver(sender_port, instance);
  }

  late final _unRegisterLogObserverPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Void>)>>(
      'LiteavFFIUnRegisterLogObserver');
  late final _unRegisterLogObserver = _unRegisterLogObserverPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>)>();

  int registerAudioFrameObserver(
      int sender_port, ffi.Pointer<ffi.Void> instance) {
    return _registerAudioFrameObserver(sender_port, instance);
  }

  late final _registerAudioFrameObserverPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Void>)>>(
      'LiteavFFIRegisterAudioFrameObserver');
  late final _registerAudioFrameObserver = _registerAudioFrameObserverPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>)>();

  int unRegisterAudioFrameObserver(
      int sender_port, ffi.Pointer<ffi.Void> instance) {
    return _unRegisterAudioFrameObserver(sender_port, instance);
  }

  late final _unRegisterAudioFrameObserverPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Void>)>>(
      'LiteavFFIUnRegisterAudioFrameObserver');
  late final _unRegisterAudioFrameObserver = _unRegisterAudioFrameObserverPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>)>();

  void startLocalPreviewTexture(
      trtc_cloud trtcsharedInstanceNativePointer, int i, int textureId) {
    return _startLocalPreviewTexture(
        trtcsharedInstanceNativePointer, i, textureId);
  }

  late final _startLocalPreviewTexturePtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(trtc_cloud, ffi.Int32, ffi.Int64)>>(
      'start_local_preview_texture');
  late final _startLocalPreviewTexture = _startLocalPreviewTexturePtr
      .asFunction<void Function(trtc_cloud, int, int)>();

  void startRemoteViewTexture(trtc_cloud trtcsharedInstanceNativePointer,
      ffi.Pointer<ffi.Int8> userId, int streamType, int textureId) {
    return _startRemoteViewTexture(
        trtcsharedInstanceNativePointer, userId, streamType, textureId);
  }

  late final _startRemoteViewTexturePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(trtc_cloud, ffi.Pointer<ffi.Int8>, ffi.Int32,
              ffi.Int64)>>('start_remote_view_texture');
  late final _startRemoteViewTexture = _startRemoteViewTexturePtr
      .asFunction<void Function(trtc_cloud, ffi.Pointer<ffi.Int8>, int, int)>();

  /// 1.1
  trtc_cloud get_instance(
    ffi.Pointer<ffi.Void> context,
  ) {
    return _get_instance(
      context,
    );
  }

  late final _get_instancePtr =
      _lookup<ffi.NativeFunction<trtc_cloud Function(ffi.Pointer<ffi.Void>)>>(
          'trtc_cloud_get_instance');
  late final _get_instance =
      _get_instancePtr.asFunction<trtc_cloud Function(ffi.Pointer<ffi.Void>)>();

  /// 1.2
  int destroy_instance(
    trtc_cloud instance,
  ) {
    return _destroy_instance(
      instance,
    );
  }

  late final _destroy_instancePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_destroy_instance');
  late final _destroy_instance =
      _destroy_instancePtr.asFunction<int Function(trtc_cloud)>();

  trtc_cloud_callback create_cloud_callback(trtc_cloud trtcCloud) {
    return _create_callback(trtcCloud);
  }

  late final _create_callbackPtr =
      _lookup<ffi.NativeFunction<trtc_cloud_callback Function(trtc_cloud)>>(
          'trtc_cloud_create_cloud_callback');
  late final _create_callback = _create_callbackPtr
      .asFunction<trtc_cloud_callback Function(trtc_cloud)>();

  void destroy_cloud_callback(trtc_cloud trtcCloud) {
    return _destroy_callback(trtcCloud);
  }

  late final _destroy_callbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(trtc_cloud_callback)>>(
          'trtc_cloud_destroy_cloud_callback');
  late final _destroy_callback =
      _destroy_callbackPtr.asFunction<void Function(trtc_cloud_callback)>();

  /// 2.1
  int enter_room(
    trtc_cloud instance,
    trtc_params_t param,
    int scene,
  ) {
    return _enter_room(
      instance,
      param,
      scene,
    );
  }

  late final _enter_roomPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              trtc_cloud, trtc_params_t, ffi.Int)>>('trtc_cloud_enter_room');
  late final _enter_room =
      _enter_roomPtr.asFunction<int Function(trtc_cloud, trtc_params_t, int)>();

  /// 2.2
  int exit_room(
    trtc_cloud instance,
  ) {
    return _exit_room(
      instance,
    );
  }

  late final _exit_roomPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_exit_room');
  late final _exit_room = _exit_roomPtr.asFunction<int Function(trtc_cloud)>();

  /// 2.3
  int switch_role(
    trtc_cloud instance,
    int role,
  ) {
    return _switch_role(
      instance,
      role,
    );
  }

  late final _switch_rolePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int)>>(
          'trtc_cloud_switch_role');
  late final _switch_role =
      _switch_rolePtr.asFunction<int Function(trtc_cloud, int)>();

  /// 2.5
  int switch_room(
    trtc_cloud instance,
    trtc_switch_room_config_t config,
  ) {
    return _switch_room(
      instance,
      config,
    );
  }

  late final _switch_roomPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud,
              trtc_switch_room_config_t)>>('trtc_cloud_switch_room');
  late final _switch_room = _switch_roomPtr
      .asFunction<int Function(trtc_cloud, trtc_switch_room_config_t)>();

  /// 2.6
  int connect_other_room(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> json_params,
  ) {
    return _connect_other_room(
      instance,
      json_params,
    );
  }

  late final _connect_other_roomPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>)>>(
      'trtc_cloud_connect_other_room');
  late final _connect_other_room = _connect_other_roomPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>)>();

  /// 2.7
  int disconnect_other_room(
    trtc_cloud instance,
  ) {
    return _disconnect_other_room(
      instance,
    );
  }

  late final _disconnect_other_roomPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_disconnect_other_room');
  late final _disconnect_other_room =
      _disconnect_other_roomPtr.asFunction<int Function(trtc_cloud)>();

  /// 2.8
  int set_default_stream_recv_mode(
    trtc_cloud instance,
    bool auto_recv_audio,
    bool auto_recv_video,
  ) {
    return _set_default_stream_recv_mode(
      instance,
      auto_recv_audio,
      auto_recv_video,
    );
  }

  late final _set_default_stream_recv_modePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Bool, ffi.Bool)>>(
      'trtc_cloud_set_default_stream_recv_mode');
  late final _set_default_stream_recv_mode = _set_default_stream_recv_modePtr
      .asFunction<int Function(trtc_cloud, bool, bool)>();

  /// 2.9
  trtc_cloud create_sub_cloud(
    trtc_cloud instance,
  ) {
    return _create_sub_cloud(
      instance,
    );
  }

  late final _create_sub_cloudPtr =
      _lookup<ffi.NativeFunction<trtc_cloud Function(trtc_cloud)>>(
          'trtc_cloud_create_sub_cloud');
  late final _create_sub_cloud =
      _create_sub_cloudPtr.asFunction<trtc_cloud Function(trtc_cloud)>();

  /// 2.10
  int destroy_sub_cloud(
    trtc_cloud instance,
    trtc_cloud sub_cloud,
  ) {
    return _destroy_sub_cloud(
      instance,
      sub_cloud,
    );
  }

  late final _destroy_sub_cloudPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, trtc_cloud)>>(
          'trtc_cloud_destroy_sub_cloud');
  late final _destroy_sub_cloud =
      _destroy_sub_cloudPtr.asFunction<int Function(trtc_cloud, trtc_cloud)>();

  /// 3.1
  int start_publishing(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> stream_id,
    int stream_type,
  ) {
    return _start_publishing(
      instance,
      stream_id,
      stream_type,
    );
  }

  late final _start_publishingPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('trtc_cloud_start_publishing');
  late final _start_publishing = _start_publishingPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int)>();

  /// 3.2
  int stop_publishing(
    trtc_cloud instance,
  ) {
    return _stop_publishing(
      instance,
    );
  }

  late final _stop_publishingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_stop_publishing');
  late final _stop_publishing =
      _stop_publishingPtr.asFunction<int Function(trtc_cloud)>();

  /// 3.5
  int set_mix_transcoding_config(
    trtc_cloud instance,
    ffi.Pointer<trtc_transcoding_config_t> config,
  ) {
    return _set_mix_transcoding_config(
      instance,
      config,
    );
  }

  late final _set_mix_transcoding_configPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  trtc_cloud, ffi.Pointer<trtc_transcoding_config_t>)>>(
      'trtc_cloud_set_mix_transcoding_config');
  late final _set_mix_transcoding_config =
      _set_mix_transcoding_configPtr.asFunction<
          int Function(trtc_cloud, ffi.Pointer<trtc_transcoding_config_t>)>();

  /// 3.6
  int start_publish_media_stream(
    trtc_cloud instance,
    ffi.Pointer<trtc_publish_target_t> target,
    ffi.Pointer<trtc_stream_encoder_param_t> params,
    ffi.Pointer<trtc_stream_mixing_config_t> config,
  ) {
    return _start_publish_media_stream(
      instance,
      target,
      params,
      config,
    );
  }

  late final _start_publish_media_streamPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  trtc_cloud,
                  ffi.Pointer<trtc_publish_target_t>,
                  ffi.Pointer<trtc_stream_encoder_param_t>,
                  ffi.Pointer<trtc_stream_mixing_config_t>)>>(
      'trtc_cloud_start_publish_media_stream');
  late final _start_publish_media_stream =
      _start_publish_media_streamPtr.asFunction<
          int Function(
              trtc_cloud,
              ffi.Pointer<trtc_publish_target_t>,
              ffi.Pointer<trtc_stream_encoder_param_t>,
              ffi.Pointer<trtc_stream_mixing_config_t>)>();

  /// 3.7
  int update_publish_media_stream(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> task_id,
    ffi.Pointer<trtc_publish_target_t> target,
    ffi.Pointer<trtc_stream_encoder_param_t> params,
    ffi.Pointer<trtc_stream_mixing_config_t> config,
  ) {
    return _update_publish_media_stream(
      instance,
      task_id,
      target,
      params,
      config,
    );
  }

  late final _update_publish_media_streamPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  trtc_cloud,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<trtc_publish_target_t>,
                  ffi.Pointer<trtc_stream_encoder_param_t>,
                  ffi.Pointer<trtc_stream_mixing_config_t>)>>(
      'trtc_cloud_update_publish_media_stream');
  late final _update_publish_media_stream =
      _update_publish_media_streamPtr.asFunction<
          int Function(
              trtc_cloud,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<trtc_publish_target_t>,
              ffi.Pointer<trtc_stream_encoder_param_t>,
              ffi.Pointer<trtc_stream_mixing_config_t>)>();

  /// 3.8
  int stop_publish_media_stream(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> taskId,
  ) {
    return _stop_publish_media_stream(
      instance,
      taskId,
    );
  }

  late final _stop_publish_media_streamPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>)>>(
      'trtc_cloud_stop_publish_media_stream');
  late final _stop_publish_media_stream = _stop_publish_media_streamPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>)>();

  /// 4.1 4.2  front_camera
  int start_local_preview(
    trtc_cloud instance,
    bool front_camera,
    tx_view view,
  ) {
    return _start_local_preview(
      instance,
      front_camera,
      view,
    );
  }

  late final _start_local_previewPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Bool, tx_view)>>(
      'trtc_cloud_start_local_preview');
  late final _start_local_preview = _start_local_previewPtr
      .asFunction<int Function(trtc_cloud, bool, tx_view)>();

  /// 4.3
  int update_local_view(
    trtc_cloud instance,
    tx_view view,
  ) {
    return _update_local_view(
      instance,
      view,
    );
  }

  late final _update_local_viewPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, tx_view)>>(
          'trtc_cloud_update_local_view');
  late final _update_local_view =
      _update_local_viewPtr.asFunction<int Function(trtc_cloud, tx_view)>();

  /// 4.4
  int stop_local_preview(
    trtc_cloud instance,
  ) {
    return _stop_local_preview(
      instance,
    );
  }

  late final _stop_local_previewPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_stop_local_preview');
  late final _stop_local_preview =
      _stop_local_previewPtr.asFunction<int Function(trtc_cloud)>();

  /// 4.5
  int mute_local_video(
    trtc_cloud instance,
    int stream_type,
    bool mute,
  ) {
    return _mute_local_video(
      instance,
      stream_type,
      mute,
    );
  }

  late final _mute_local_videoPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int, ffi.Bool)>>(
      'trtc_cloud_mute_local_video');
  late final _mute_local_video =
      _mute_local_videoPtr.asFunction<int Function(trtc_cloud, int, bool)>();

  /// 4.6
  int set_video_mute_image(
    trtc_cloud instance,
    ffi.Pointer<trtc_image_buffer_t> image,
    int fps,
  ) {
    return _set_video_mute_image(
      instance,
      image,
      fps,
    );
  }

  late final _set_video_mute_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<trtc_image_buffer_t>,
              ffi.Int)>>('trtc_cloud_set_video_mute_image');
  late final _set_video_mute_image = _set_video_mute_imagePtr.asFunction<
      int Function(trtc_cloud, ffi.Pointer<trtc_image_buffer_t>, int)>();

  /// 4.7
  int start_remote_view(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int stream_type,
    tx_view view,
  ) {
    return _start_remote_view(
      instance,
      user_id,
      stream_type,
      view,
    );
  }

  late final _start_remote_viewPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>, ffi.Int,
              tx_view)>>('trtc_cloud_start_remote_view');
  late final _start_remote_view = _start_remote_viewPtr.asFunction<
      int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int, tx_view)>();

  /// 4.8
  int update_remote_view(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int stream_type,
    tx_view view,
  ) {
    return _update_remote_view(
      instance,
      user_id,
      stream_type,
      view,
    );
  }

  late final _update_remote_viewPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>, ffi.Int,
              tx_view)>>('trtc_cloud_update_remote_view');
  late final _update_remote_view = _update_remote_viewPtr.asFunction<
      int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int, tx_view)>();

  /// 4.9
  int stop_remote_view(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int stream_type,
  ) {
    return _stop_remote_view(
      instance,
      user_id,
      stream_type,
    );
  }

  late final _stop_remote_viewPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('trtc_cloud_stop_remote_view');
  late final _stop_remote_view = _stop_remote_viewPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int)>();

  /// 4.10
  int stop_all_remote_view(
    trtc_cloud instance,
  ) {
    return _stop_all_remote_view(
      instance,
    );
  }

  late final _stop_all_remote_viewPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_stop_all_remote_view');
  late final _stop_all_remote_view =
      _stop_all_remote_viewPtr.asFunction<int Function(trtc_cloud)>();

  /// 4.12
  int mute_all_remote_video_streams(
    trtc_cloud instance,
    bool mute,
  ) {
    return _mute_all_remote_video_streams(
      instance,
      mute,
    );
  }

  late final _mute_all_remote_video_streamsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Bool)>>(
          'trtc_cloud_mute_all_remote_video_streams');
  late final _mute_all_remote_video_streams = _mute_all_remote_video_streamsPtr
      .asFunction<int Function(trtc_cloud, bool)>();

  /// 4.13
  int set_video_encoder_param(
    trtc_cloud instance,
    trtc_video_enc_param_t param,
  ) {
    return _set_video_encoder_param(
      instance,
      param,
    );
  }

  late final _set_video_encoder_paramPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud,
              trtc_video_enc_param_t)>>('trtc_cloud_set_video_encoder_param');
  late final _set_video_encoder_param = _set_video_encoder_paramPtr
      .asFunction<int Function(trtc_cloud, trtc_video_enc_param_t)>();

  /// 4.14
  int set_network_qos_param(
    trtc_cloud instance,
    trtc_network_qos_param_t param,
  ) {
    return _set_network_qos_param(
      instance,
      param,
    );
  }

  late final _set_network_qos_paramPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud,
              trtc_network_qos_param_t)>>('trtc_cloud_set_network_qos_param');
  late final _set_network_qos_param = _set_network_qos_paramPtr
      .asFunction<int Function(trtc_cloud, trtc_network_qos_param_t)>();

  /// 4.15
  int set_local_render_params(
    trtc_cloud instance,
    int video_rotation,
    int fill_mode,
    int mirror_type,
  ) {
    return _set_local_render_params(
      instance,
      video_rotation,
      fill_mode,
      mirror_type,
    );
  }

  late final _set_local_render_paramsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Int, ffi.Int,
              ffi.Int)>>('trtc_cloud_set_local_render_params');
  late final _set_local_render_params = _set_local_render_paramsPtr
      .asFunction<int Function(trtc_cloud, int, int, int)>();

  /// 4.16
  int set_remote_render_params(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int stream_type,
    trtc_render_params_t param,
  ) {
    return _set_remote_render_params(
      instance,
      user_id,
      stream_type,
      param,
    );
  }

  late final _set_remote_render_paramsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>, ffi.Int,
              trtc_render_params_t)>>('trtc_cloud_set_remote_render_params');
  late final _set_remote_render_params =
      _set_remote_render_paramsPtr.asFunction<
          int Function(
              trtc_cloud, ffi.Pointer<ffi.Char>, int, trtc_render_params_t)>();

  /// 4.17
  int set_video_encoder_rotation(
    trtc_cloud instance,
    int rotation,
  ) {
    return _set_video_encoder_rotation(
      instance,
      rotation,
    );
  }

  late final _set_video_encoder_rotationPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int)>>(
          'trtc_cloud_set_video_encoder_rotation');
  late final _set_video_encoder_rotation = _set_video_encoder_rotationPtr
      .asFunction<int Function(trtc_cloud, int)>();

  /// 4.18
  int set_video_encoder_mirror(
    trtc_cloud instance,
    bool mirror,
  ) {
    return _set_video_encoder_mirror(
      instance,
      mirror,
    );
  }

  late final _set_video_encoder_mirrorPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Bool)>>(
          'trtc_cloud_set_video_encoder_mirror');
  late final _set_video_encoder_mirror =
      _set_video_encoder_mirrorPtr.asFunction<int Function(trtc_cloud, bool)>();

  /// 4.20
  int enable_small_video_stream(
    trtc_cloud instance,
    bool enable,
    trtc_video_enc_param_t param,
  ) {
    return _enable_small_video_stream(
      instance,
      enable,
      param,
    );
  }

  late final _enable_small_video_streamPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Bool,
              trtc_video_enc_param_t)>>('trtc_cloud_enable_small_video_stream');
  late final _enable_small_video_stream = _enable_small_video_streamPtr
      .asFunction<int Function(trtc_cloud, bool, trtc_video_enc_param_t)>();

  /// 4.21
  int set_remote_video_stream_type(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int type,
  ) {
    return _set_remote_video_stream_type(
      instance,
      user_id,
      type,
    );
  }

  late final _set_remote_video_stream_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('trtc_cloud_set_remote_video_stream_type');
  late final _set_remote_video_stream_type = _set_remote_video_stream_typePtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int)>();

  /// 4.22
  int mute_remote_video_stream(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int stream_type,
    bool mute,
  ) {
    return _mute_remote_video_stream(
      instance,
      user_id,
      stream_type,
      mute,
    );
  }

  late final _mute_remote_video_streamPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>, ffi.Int,
              ffi.Bool)>>('trtc_cloud_mute_remote_video_stream');
  late final _mute_remote_video_stream = _mute_remote_video_streamPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int, bool)>();

  /// 4.23
  int snapshot_video(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int stream_type,
    int source_type,
  ) {
    return _snapshot_video(
      instance,
      user_id,
      stream_type,
      source_type,
    );
  }

  late final _snapshot_videoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>, ffi.Int,
              ffi.Int)>>('trtc_cloud_snapshot_video');
  late final _snapshot_video = _snapshot_videoPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int, int)>();

  /// 5.1
  int start_local_audio(
    trtc_cloud instance,
    int quality,
  ) {
    return _start_local_audio(
      instance,
      quality,
    );
  }

  late final _start_local_audioPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int)>>(
          'trtc_cloud_start_local_audio');
  late final _start_local_audio =
      _start_local_audioPtr.asFunction<int Function(trtc_cloud, int)>();

  /// 5.2
  int stop_local_audio(
    trtc_cloud instance,
  ) {
    return _stop_local_audio(
      instance,
    );
  }

  late final _stop_local_audioPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_stop_local_audio');
  late final _stop_local_audio =
      _stop_local_audioPtr.asFunction<int Function(trtc_cloud)>();

  /// 5.3
  int mute_local_audio(
    trtc_cloud instance,
    bool mute,
  ) {
    return _mute_local_audio(
      instance,
      mute,
    );
  }

  late final _mute_local_audioPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Bool)>>(
          'trtc_cloud_mute_local_audio');
  late final _mute_local_audio =
      _mute_local_audioPtr.asFunction<int Function(trtc_cloud, bool)>();

  /// 5.4
  int mute_remote_audio(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    bool mute,
  ) {
    return _mute_remote_audio(
      instance,
      user_id,
      mute,
    );
  }

  late final _mute_remote_audioPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>,
              ffi.Bool)>>('trtc_cloud_mute_remote_audio');
  late final _mute_remote_audio = _mute_remote_audioPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>, bool)>();

  /// 5.5
  int mute_all_remote_audio(
    trtc_cloud instance,
    bool mute,
  ) {
    return _mute_all_remote_audio(
      instance,
      mute,
    );
  }

  late final _mute_all_remote_audioPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Bool)>>(
          'trtc_cloud_mute_all_remote_audio');
  late final _mute_all_remote_audio =
      _mute_all_remote_audioPtr.asFunction<int Function(trtc_cloud, bool)>();

  /// 5.7
  int set_remote_audio_volume(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int volume,
  ) {
    return _set_remote_audio_volume(
      instance,
      user_id,
      volume,
    );
  }

  late final _set_remote_audio_volumePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('trtc_cloud_set_remote_audio_volume');
  late final _set_remote_audio_volume = _set_remote_audio_volumePtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int)>();

  /// 5.8
  int set_audio_capture_volume(
    trtc_cloud instance,
    int volume,
  ) {
    return _set_audio_capture_volume(
      instance,
      volume,
    );
  }

  late final _set_audio_capture_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int)>>(
          'trtc_cloud_set_audio_capture_volume');
  late final _set_audio_capture_volume =
      _set_audio_capture_volumePtr.asFunction<int Function(trtc_cloud, int)>();

  /// 5.9
  int get_audio_capture_volume(
    trtc_cloud instance,
  ) {
    return _get_audio_capture_volume(
      instance,
    );
  }

  late final _get_audio_capture_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_get_audio_capture_volume');
  late final _get_audio_capture_volume =
      _get_audio_capture_volumePtr.asFunction<int Function(trtc_cloud)>();

  /// 5.10
  int set_audio_playout_volume(
    trtc_cloud instance,
    int volume,
  ) {
    return _set_audio_playout_volume(
      instance,
      volume,
    );
  }

  late final _set_audio_playout_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int)>>(
          'trtc_cloud_set_audio_playout_volume');
  late final _set_audio_playout_volume =
      _set_audio_playout_volumePtr.asFunction<int Function(trtc_cloud, int)>();

  /// 5.11
  int get_audio_playout_volume(
    trtc_cloud instance,
  ) {
    return _get_audio_playout_volume(
      instance,
    );
  }

  late final _get_audio_playout_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_get_audio_playout_volume');
  late final _get_audio_playout_volume =
      _get_audio_playout_volumePtr.asFunction<int Function(trtc_cloud)>();

  /// 5.12
  int enable_audio_volume_evaluation(
    trtc_cloud instance,
    bool enable,
    trtc_audio_volume_evaluate_params_t params,
  ) {
    return _enable_audio_volume_evaluation(
      instance,
      enable,
      params,
    );
  }

  late final _enable_audio_volume_evaluationPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  trtc_cloud, ffi.Bool, trtc_audio_volume_evaluate_params_t)>>(
      'trtc_cloud_enable_audio_volume_evaluation');
  late final _enable_audio_volume_evaluation =
      _enable_audio_volume_evaluationPtr.asFunction<
          int Function(
              trtc_cloud, bool, trtc_audio_volume_evaluate_params_t)>();

  /// 5.15
  int start_local_recording(
    trtc_cloud instance,
    trtc_local_recording_params_t params,
  ) {
    return _start_local_recording(
      instance,
      params,
    );
  }

  late final _start_local_recordingPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(trtc_cloud, trtc_local_recording_params_t)>>(
      'trtc_cloud_start_local_recording');
  late final _start_local_recording = _start_local_recordingPtr
      .asFunction<int Function(trtc_cloud, trtc_local_recording_params_t)>();

  /// 5.16
  int stop_local_recording(
    trtc_cloud instance,
  ) {
    return _stop_local_recording(
      instance,
    );
  }

  late final _stop_local_recordingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_stop_local_recording');
  late final _stop_local_recording =
      _stop_local_recordingPtr.asFunction<int Function(trtc_cloud)>();

  /// 5.17
  int set_gravity_sensor_adaptive_mode(
    trtc_cloud instance,
    int mode,
  ) {
    return _set_gravity_sensor_adaptive_mode(
      instance,
      mode,
    );
  }

  late final _set_gravity_sensor_adaptive_modePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int)>>(
          'trtc_cloud_set_gravity_sensor_adaptive_mode');
  late final _set_gravity_sensor_adaptive_mode =
      _set_gravity_sensor_adaptive_modePtr
          .asFunction<int Function(trtc_cloud, int)>();

  /// 6.1
  tx_device_manager get_device_manager(
    trtc_cloud instance,
  ) {
    return _get_device_manager(
      instance,
    );
  }

  late final _get_device_managerPtr =
      _lookup<ffi.NativeFunction<tx_device_manager Function(trtc_cloud)>>(
          'trtc_cloud_get_device_manager');
  late final _get_device_manager = _get_device_managerPtr
      .asFunction<tx_device_manager Function(trtc_cloud)>();

  /// 7.1
  int set_beauty_style(
    trtc_cloud instance,
    int style,
    int beauty,
    int white,
    int ruddiness,
  ) {
    return _set_beauty_style(
      instance,
      style,
      beauty,
      white,
      ruddiness,
    );
  }

  late final _set_beauty_stylePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Int, ffi.Uint32, ffi.Uint32,
              ffi.Uint32)>>('trtc_cloud_set_beauty_style');
  late final _set_beauty_style = _set_beauty_stylePtr
      .asFunction<int Function(trtc_cloud, int, int, int, int)>();

  /// 7.2
  int set_water_mark(
    trtc_cloud instance,
    int stream_type,
    ffi.Pointer<ffi.Char> src_data,
    int src_type,
    int width,
    int height,
    double x_offset,
    double y_offset,
    double f_width_ratio,
    bool is_visible_on_local_preview,
  ) {
    return _set_water_mark(
      instance,
      stream_type,
      src_data,
      src_type,
      width,
      height,
      x_offset,
      y_offset,
      f_width_ratio,
      is_visible_on_local_preview,
    );
  }

  late final _set_water_markPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              trtc_cloud,
              ffi.Int,
              ffi.Pointer<ffi.Char>,
              ffi.Int,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Bool)>>('trtc_cloud_set_water_mark');
  late final _set_water_mark = _set_water_markPtr.asFunction<
      int Function(trtc_cloud, int, ffi.Pointer<ffi.Char>, int, int, int,
          double, double, double, bool)>();

  /// 7.3
  tx_beauty_manager get_beauty_manager(
    trtc_cloud instance,
  ) {
    return _get_beauty_manager(
      instance,
    );
  }

  late final _get_beauty_managerPtr =
      _lookup<ffi.NativeFunction<tx_beauty_manager Function(trtc_cloud)>>(
          'trtc_cloud_get_beauty_manager');
  late final _get_beauty_manager = _get_beauty_managerPtr
      .asFunction<tx_beauty_manager Function(trtc_cloud)>();

  /// 8.1
  tx_audio_effect_manager get_audio_effect_manager(
    trtc_cloud instance,
  ) {
    return _get_audio_effect_manager(
      instance,
    );
  }

  late final _get_audio_effect_managerPtr =
      _lookup<ffi.NativeFunction<tx_audio_effect_manager Function(trtc_cloud)>>(
          'trtc_cloud_get_audio_effect_manager');
  late final _get_audio_effect_manager = _get_audio_effect_managerPtr
      .asFunction<tx_audio_effect_manager Function(trtc_cloud)>();

  /// 8.2 TARGET_PLATFORM_DESKTOP
  int start_system_audio_loopback(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> device_name,
  ) {
    return _start_system_audio_loopback(
      instance,
      device_name,
    );
  }

  late final _start_system_audio_loopbackPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>)>>(
      'trtc_cloud_start_system_audio_loopback');
  late final _start_system_audio_loopback = _start_system_audio_loopbackPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Char>)>();

  /// 8.3 TARGET_PLATFORM_DESKTOP
  int stop_system_audio_loopback(
    trtc_cloud instance,
  ) {
    return _stop_system_audio_loopback(
      instance,
    );
  }

  late final _stop_system_audio_loopbackPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_stop_system_audio_loopback');
  late final _stop_system_audio_loopback =
      _stop_system_audio_loopbackPtr.asFunction<int Function(trtc_cloud)>();

  /// 8.4
  int set_system_audio_loopback_volume(
    trtc_cloud instance,
    int volume,
  ) {
    return _set_system_audio_loopback_volume(
      instance,
      volume,
    );
  }

  late final _set_system_audio_loopback_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Uint32)>>(
          'trtc_cloud_set_system_audio_loopback_volume');
  late final _set_system_audio_loopback_volume =
      _set_system_audio_loopback_volumePtr
          .asFunction<int Function(trtc_cloud, int)>();

  /// 9.1
  int start_screen_capture(
    trtc_cloud instance,
    tx_view view,
    int type,
    ffi.Pointer<trtc_video_enc_param_t> param,
  ) {
    return _start_screen_capture(
      instance,
      view,
      type,
      param,
    );
  }

  late final _start_screen_capturePtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(trtc_cloud, tx_view, ffi.Int,
                  ffi.Pointer<trtc_video_enc_param_t>)>>(
      'trtc_cloud_start_screen_capture');
  late final _start_screen_capture = _start_screen_capturePtr.asFunction<
      int Function(
          trtc_cloud, tx_view, int, ffi.Pointer<trtc_video_enc_param_t>)>();

  /// 9.2
  int stop_screen_capture(
    trtc_cloud instance,
  ) {
    return _stop_screen_capture(
      instance,
    );
  }

  late final _stop_screen_capturePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_stop_screen_capture');
  late final _stop_screen_capture =
      _stop_screen_capturePtr.asFunction<int Function(trtc_cloud)>();

  /// 9.3
  int pause_screen_capture(
    trtc_cloud instance,
  ) {
    return _pause_screen_capture(
      instance,
    );
  }

  late final _pause_screen_capturePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_pause_screen_capture');
  late final _pause_screen_capture =
      _pause_screen_capturePtr.asFunction<int Function(trtc_cloud)>();

  /// 9.4
  int resume_screen_capture(
    trtc_cloud instance,
  ) {
    return _resume_screen_capture(
      instance,
    );
  }

  late final _resume_screen_capturePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_resume_screen_capture');
  late final _resume_screen_capture =
      _resume_screen_capturePtr.asFunction<int Function(trtc_cloud)>();

  /// 9.5 TARGET_PLATFORM_DESKTOP
  int get_screen_capture_source_list(
    trtc_cloud instance,
    trtc_size_t thumbnail,
    trtc_size_t icon,
    ffi.Pointer<trtc_screen_capture_source_list> source_list,
    ffi.Pointer<ffi.Int> count,
  ) {
    return _get_screen_capture_source_list(
      instance,
      thumbnail,
      icon,
      source_list,
      count,
    );
  }

  late final _get_screen_capture_source_listPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  trtc_cloud,
                  trtc_size_t,
                  trtc_size_t,
                  ffi.Pointer<trtc_screen_capture_source_list>,
                  ffi.Pointer<ffi.Int>)>>(
      'trtc_cloud_get_screen_capture_source_list');
  late final _get_screen_capture_source_list =
      _get_screen_capture_source_listPtr.asFunction<
          int Function(
              trtc_cloud,
              trtc_size_t,
              trtc_size_t,
              ffi.Pointer<trtc_screen_capture_source_list>,
              ffi.Pointer<ffi.Int>)>();

  int get_screen_capture_sources_info(
    trtc_screen_capture_source_list source_list,
    int index,
    ffi.Pointer<trtc_screen_capture_source_info_t> source_info,
  ) {
    return _get_screen_capture_sources_info(
      source_list,
      index,
      source_info,
    );
  }

  late final _get_screen_capture_sources_infoPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(trtc_screen_capture_source_list, ffi.Int,
                  ffi.Pointer<trtc_screen_capture_source_info_t>)>>(
      'trtc_cloud_get_screen_capture_sources_info');
  late final _get_screen_capture_sources_info =
      _get_screen_capture_sources_infoPtr.asFunction<
          int Function(trtc_screen_capture_source_list, int,
              ffi.Pointer<trtc_screen_capture_source_info_t>)>();

  void release_screen_capture_sources_list(
    trtc_screen_capture_source_list source_list,
  ) {
    return _release_screen_capture_sources_list(
      source_list,
    );
  }

  late final _release_screen_capture_sources_listPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(trtc_screen_capture_source_list)>>(
      'trtc_cloud_release_screen_capture_sources_list');
  late final _release_screen_capture_sources_list =
      _release_screen_capture_sources_listPtr
          .asFunction<void Function(trtc_screen_capture_source_list)>();

  /// 9.6 TARGET_PLATFORM_DESKTOP
  int select_screen_capture_target(
    trtc_cloud instance,
    trtc_screen_capture_source_info_t source,
    trtc_rect_t capture_rect,
    trtc_screen_capture_property_t property,
  ) {
    return _select_screen_capture_target(
      instance,
      source,
      capture_rect,
      property,
    );
  }

  late final _select_screen_capture_targetPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(trtc_cloud, trtc_screen_capture_source_info_t,
                  trtc_rect_t, trtc_screen_capture_property_t)>>(
      'trtc_cloud_select_screen_capture_target');
  late final _select_screen_capture_target =
      _select_screen_capture_targetPtr.asFunction<
          int Function(trtc_cloud, trtc_screen_capture_source_info_t,
              trtc_rect_t, trtc_screen_capture_property_t)>();

  /// 9.8 TARGET_PLATFORM_DESKTOP
  int add_excluded_share_window(
    trtc_cloud instance,
    tx_view window_id,
  ) {
    return _add_excluded_share_window(
      instance,
      window_id,
    );
  }

  late final _add_excluded_share_windowPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, tx_view)>>(
          'trtc_cloud_add_excluded_share_window');
  late final _add_excluded_share_window = _add_excluded_share_windowPtr
      .asFunction<int Function(trtc_cloud, tx_view)>();

  /// 9.9 TARGET_PLATFORM_DESKTOP
  int remove_excluded_share_window(
    trtc_cloud instance,
    tx_view window_id,
  ) {
    return _remove_excluded_share_window(
      instance,
      window_id,
    );
  }

  late final _remove_excluded_share_windowPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, tx_view)>>(
          'trtc_cloud_remove_excluded_share_window');
  late final _remove_excluded_share_window = _remove_excluded_share_windowPtr
      .asFunction<int Function(trtc_cloud, tx_view)>();

  /// 9.10 TARGET_PLATFORM_DESKTOP
  int remove_all_excluded_share_windows(
    trtc_cloud instance,
  ) {
    return _remove_all_excluded_share_windows(
      instance,
    );
  }

  late final _remove_all_excluded_share_windowsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_remove_all_excluded_share_windows');
  late final _remove_all_excluded_share_windows =
      _remove_all_excluded_share_windowsPtr
          .asFunction<int Function(trtc_cloud)>();

  /// 9.11 TARGET_PLATFORM_DESKTOP
  int add_included_share_window(
    trtc_cloud instance,
    tx_view window_id,
  ) {
    return _add_included_share_window(
      instance,
      window_id,
    );
  }

  late final _add_included_share_windowPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, tx_view)>>(
          'trtc_cloud_add_included_share_window');
  late final _add_included_share_window = _add_included_share_windowPtr
      .asFunction<int Function(trtc_cloud, tx_view)>();

  /// 9.12 TARGET_PLATFORM_DESKTOP
  int remove_included_share_window(
    trtc_cloud instance,
    tx_view window_id,
  ) {
    return _remove_included_share_window(
      instance,
      window_id,
    );
  }

  late final _remove_included_share_windowPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, tx_view)>>(
          'trtc_cloud_remove_included_share_window');
  late final _remove_included_share_window = _remove_included_share_windowPtr
      .asFunction<int Function(trtc_cloud, tx_view)>();

  /// 9.13 TARGET_PLATFORM_DESKTOP
  int remove_all_included_share_windows(
    trtc_cloud instance,
  ) {
    return _remove_all_included_share_windows(
      instance,
    );
  }

  late final _remove_all_included_share_windowsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_remove_all_included_share_windows');
  late final _remove_all_included_share_windows =
      _remove_all_included_share_windowsPtr
          .asFunction<int Function(trtc_cloud)>();

  /// 9.7
  int set_sub_stream_encoder_param(
    trtc_cloud instance,
    int video_resolution,
    int res_mode,
    int video_fps,
    int video_bitrate,
    int min_video_bitrate,
    bool enable_adjust_res,
  ) {
    return _set_sub_stream_encoder_param(
      instance,
      video_resolution,
      res_mode,
      video_fps,
      video_bitrate,
      min_video_bitrate,
      enable_adjust_res,
    );
  }

  late final _set_sub_stream_encoder_paramPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              trtc_cloud,
              ffi.Int,
              ffi.Int,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Bool)>>('trtc_cloud_set_sub_stream_encoder_param');
  late final _set_sub_stream_encoder_param = _set_sub_stream_encoder_paramPtr
      .asFunction<int Function(trtc_cloud, int, int, int, int, int, bool)>();

  /// 10.1
  int enable_custom_video_capture(
    trtc_cloud instance,
    int stream_ype,
    bool enable,
  ) {
    return _enable_custom_video_capture(
      instance,
      stream_ype,
      enable,
    );
  }

  late final _enable_custom_video_capturePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int, ffi.Bool)>>(
      'trtc_cloud_enable_custom_video_capture');
  late final _enable_custom_video_capture = _enable_custom_video_capturePtr
      .asFunction<int Function(trtc_cloud, int, bool)>();

  /// 10.2
  int send_custom_video_data(
    trtc_cloud instance,
    int stream_type,
    trtc_video_frame_t frame,
  ) {
    return _send_custom_video_data(
      instance,
      stream_type,
      frame,
    );
  }

  late final _send_custom_video_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Int,
              trtc_video_frame_t)>>('trtc_cloud_send_custom_video_data');
  late final _send_custom_video_data = _send_custom_video_dataPtr
      .asFunction<int Function(trtc_cloud, int, trtc_video_frame_t)>();

  /// 10.3
  int enable_custom_audio_capture(
    trtc_cloud instance,
    bool enable,
  ) {
    return _enable_custom_audio_capture(
      instance,
      enable,
    );
  }

  late final _enable_custom_audio_capturePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Bool)>>(
          'trtc_cloud_enable_custom_audio_capture');
  late final _enable_custom_audio_capture = _enable_custom_audio_capturePtr
      .asFunction<int Function(trtc_cloud, bool)>();

  /// 10.4
  int send_custom_audio_data(
    trtc_cloud instance,
    trtc_audio_frame_t frame,
  ) {
    return _send_custom_audio_data(
      instance,
      frame,
    );
  }

  late final _send_custom_audio_dataPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(trtc_cloud, trtc_audio_frame_t)>>(
      'trtc_cloud_send_custom_audio_data');
  late final _send_custom_audio_data = _send_custom_audio_dataPtr
      .asFunction<int Function(trtc_cloud, trtc_audio_frame_t)>();

  /// 10.5
  int enable_mix_external_audio_frame(
    trtc_cloud instance,
    bool enable_publish,
    bool enable_playout,
  ) {
    return _enable_mix_external_audio_frame(
      instance,
      enable_publish,
      enable_playout,
    );
  }

  late final _enable_mix_external_audio_framePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Bool, ffi.Bool)>>(
      'trtc_cloud_enable_mix_external_audio_frame');
  late final _enable_mix_external_audio_frame =
      _enable_mix_external_audio_framePtr
          .asFunction<int Function(trtc_cloud, bool, bool)>();

  /// 10.9.1
  int enable_local_video_custom_process(
    trtc_cloud instance,
    bool enable,
    int pixel_format,
    int buffer_type,
  ) {
    return _enable_local_video_custom_process(
      instance,
      enable,
      pixel_format,
      buffer_type,
    );
  }

  late final _enable_local_video_custom_processPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Bool, ffi.Int,
              ffi.Int)>>('trtc_cloud_enable_local_video_custom_process');
  late final _enable_local_video_custom_process =
      _enable_local_video_custom_processPtr
          .asFunction<int Function(trtc_cloud, bool, int, int)>();

  /// 10.9.2
  int set_local_video_custom_process_callback(
    trtc_cloud instance,
    trtc_video_frame_callback callback,
  ) {
    return _set_local_video_custom_process_callback(
      instance,
      callback,
    );
  }

  late final _set_local_video_custom_process_callbackPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(trtc_cloud, trtc_video_frame_callback)>>(
      'trtc_cloud_set_local_video_custom_process_callback');
  late final _set_local_video_custom_process_callback =
      _set_local_video_custom_process_callbackPtr
          .asFunction<int Function(trtc_cloud, trtc_video_frame_callback)>();

  /// 10.10
  int set_local_video_render_callback(
    trtc_cloud instance,
    int pixel_format,
    int buffer_type,
    trtc_video_frame_callback callback,
  ) {
    return _set_local_video_render_callback(
      instance,
      pixel_format,
      buffer_type,
      callback,
    );
  }

  late final _set_local_video_render_callbackPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  trtc_cloud, ffi.Int, ffi.Int, trtc_video_frame_callback)>>(
      'trtc_cloud_set_local_video_render_callback');
  late final _set_local_video_render_callback =
      _set_local_video_render_callbackPtr.asFunction<
          int Function(trtc_cloud, int, int, trtc_video_frame_callback)>();

  /// 10.11
  int set_remote_video_render_callback(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> user_id,
    int pixel_format,
    int buffer_type,
    trtc_video_render_callback callback,
  ) {
    return _set_remote_video_render_callback(
      instance,
      user_id,
      pixel_format,
      buffer_type,
      callback,
    );
  }

  late final _set_remote_video_render_callbackPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Char>, ffi.Int,
                  ffi.Int, trtc_video_render_callback)>>(
      'trtc_cloud_set_remote_video_render_callback');
  late final _set_remote_video_render_callback =
      _set_remote_video_render_callbackPtr.asFunction<
          int Function(trtc_cloud, ffi.Pointer<ffi.Char>, int, int,
              trtc_video_render_callback)>();

  /// 10.12
  int set_audio_frame_callback(
    trtc_cloud instance,
    trtc_audio_frame_callback callback,
  ) {
    return _set_audio_frame_callback(
      instance,
      callback,
    );
  }

  late final _set_audio_frame_callbackPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(trtc_cloud, trtc_audio_frame_callback)>>(
      'trtc_cloud_set_audio_frame_callback');
  late final _set_audio_frame_callback = _set_audio_frame_callbackPtr
      .asFunction<int Function(trtc_cloud, trtc_audio_frame_callback)>();

  /// 11.1
  int send_sustom_cmd_msg(
    trtc_cloud instance,
    int cmd_id,
    ffi.Pointer<ffi.Uint8> data,
    int data_size,
    bool reliable,
    bool ordered,
  ) {
    return _send_sustom_cmd_msg(
      instance,
      cmd_id,
      data,
      data_size,
      reliable,
      ordered,
    );
  }

  late final _send_sustom_cmd_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Int, ffi.Pointer<ffi.Uint8>, ffi.Int,
              ffi.Bool, ffi.Bool)>>('trtc_cloud_send_sustom_cmd_msg');
  late final _send_sustom_cmd_msg = _send_sustom_cmd_msgPtr.asFunction<
      int Function(trtc_cloud, int, ffi.Pointer<ffi.Uint8>, int, bool, bool)>();

  /// 11.2
  int send_sei_msg(
    trtc_cloud instance,
    ffi.Pointer<ffi.Uint8> data,
    int data_size,
    int repeat_count,
  ) {
    return _send_sei_msg(
      instance,
      data,
      data_size,
      repeat_count,
    );
  }

  late final _send_sei_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud, ffi.Pointer<ffi.Uint8>, ffi.Int,
              ffi.Int)>>('trtc_cloud_send_sei_msg');
  late final _send_sei_msg = _send_sei_msgPtr
      .asFunction<int Function(trtc_cloud, ffi.Pointer<ffi.Uint8>, int, int)>();

  /// 12.1
  int start_speed_test(
    trtc_cloud instance,
    trtc_speed_test_params_t params,
  ) {
    return _start_speed_test(
      instance,
      params,
    );
  }

  late final _start_speed_testPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(trtc_cloud,
              trtc_speed_test_params_t)>>('trtc_cloud_start_speed_test');
  late final _start_speed_test = _start_speed_testPtr
      .asFunction<int Function(trtc_cloud, trtc_speed_test_params_t)>();

  /// 12.2
  int stop_speed_test(
    trtc_cloud instance,
  ) {
    return _stop_speed_test(
      instance,
    );
  }

  late final _stop_speed_testPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud)>>(
          'trtc_cloud_stop_speed_test');
  late final _stop_speed_test =
      _stop_speed_testPtr.asFunction<int Function(trtc_cloud)>();

  /// 13.1
  ffi.Pointer<ffi.Char> get_sdk_version(
    trtc_cloud instance,
  ) {
    return _get_sdk_version(
      instance,
    );
  }

  late final _get_sdk_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(trtc_cloud)>>(
          'trtc_cloud_get_sdk_version');
  late final _get_sdk_version = _get_sdk_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(trtc_cloud)>();

  /// 13.2 - 13.5
  int set_log_param(
    trtc_cloud instance,
    trtc_log_param_t param,
  ) {
    return _set_log_param(
      instance,
      param,
    );
  }

  late final _set_log_paramPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(trtc_cloud, trtc_log_param_t)>>(
      'trtc_cloud_set_log_param');
  late final _set_log_param = _set_log_paramPtr
      .asFunction<int Function(trtc_cloud, trtc_log_param_t)>();

  /// 13.6
  int set_log_callback(
    trtc_cloud instance,
    trtc_log_callback callback,
  ) {
    return _set_log_callback(
      instance,
      callback,
    );
  }

  late final _set_log_callbackPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(trtc_cloud, trtc_log_callback)>>(
      'trtc_cloud_set_log_callback');
  late final _set_log_callback = _set_log_callbackPtr
      .asFunction<int Function(trtc_cloud, trtc_log_callback)>();

  /// 13.7
  int show_debug_view(
    trtc_cloud instance,
    int show_type,
  ) {
    return _show_debug_view(
      instance,
      show_type,
    );
  }

  late final _show_debug_viewPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(trtc_cloud, ffi.Int)>>(
          'trtc_cloud_show_debug_view');
  late final _show_debug_view =
      _show_debug_viewPtr.asFunction<int Function(trtc_cloud, int)>();

  /// 13.9
  ffi.Pointer<ffi.Char> call_experimental_api(
    trtc_cloud instance,
    ffi.Pointer<ffi.Char> json_str,
  ) {
    return _call_experimental_api(
      instance,
      json_str,
    );
  }

  late final _call_experimental_apiPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(trtc_cloud,
              ffi.Pointer<ffi.Char>)>>('trtc_cloud_call_experimental_api');
  late final _call_experimental_api = _call_experimental_apiPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(trtc_cloud, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Void> copy_native_memery(
    ffi.Pointer<ffi.Void> dst,
    ffi.Pointer<ffi.Void> src,
    int size,
  ) {
    return _copy_native_memery(
      dst,
      src,
      size,
    );
  }

  late final _copy_native_memeryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Int)>>('trtc_cloud_copy_native_memery');
  late final _copy_native_memery = _copy_native_memeryPtr.asFunction<
      ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, int)>();

  void write_log(
    int log_write_level,
    ffi.Pointer<ffi.Char> log_file_line,
    ffi.Pointer<ffi.Char> log_tag,
    ffi.Pointer<ffi.Char> log_message,
  ) {
    _write_log(log_write_level, log_file_line, log_tag, log_message);
  }

  late final _write_logPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('trtc_cloud_write_log');
  late final _write_log = _write_logPtr.asFunction<
      ffi.Pointer<ffi.Void> Function(int, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  int tx_beauty_manager_set_beauty_style(
    tx_beauty_manager instance,
    int style,
  ) {
    return _tx_beauty_manager_set_beauty_style(
      instance,
      style,
    );
  }

  late final _tx_beauty_manager_set_beauty_stylePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(tx_beauty_manager, ffi.Int)>>(
          'tx_beauty_manager_set_beauty_style');
  late final _tx_beauty_manager_set_beauty_style =
      _tx_beauty_manager_set_beauty_stylePtr
          .asFunction<int Function(tx_beauty_manager, int)>();

  int tx_beauty_manager_set_beauty_level(
    tx_beauty_manager instance,
    int level,
  ) {
    return _tx_beauty_manager_set_beauty_level(
      instance,
      level,
    );
  }

  late final _tx_beauty_manager_set_beauty_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(tx_beauty_manager, ffi.Int)>>(
          'tx_beauty_manager_set_beauty_level');
  late final _tx_beauty_manager_set_beauty_level =
      _tx_beauty_manager_set_beauty_levelPtr
          .asFunction<int Function(tx_beauty_manager, int)>();

  int tx_beauty_manager_set_whiteness_level(
    tx_beauty_manager instance,
    int level,
  ) {
    return _tx_beauty_manager_set_whiteness_level(
      instance,
      level,
    );
  }

  late final _tx_beauty_manager_set_whiteness_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(tx_beauty_manager, ffi.Int)>>(
          'tx_beauty_manager_set_whiteness_level');
  late final _tx_beauty_manager_set_whiteness_level =
      _tx_beauty_manager_set_whiteness_levelPtr
          .asFunction<int Function(tx_beauty_manager, int)>();

  int tx_beauty_manager_enable_sharpness_enhancement(
    tx_beauty_manager instance,
    bool enable,
  ) {
    return _tx_beauty_manager_enable_sharpness_enhancement(
      instance,
      enable,
    );
  }

  late final _tx_beauty_manager_enable_sharpness_enhancementPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(tx_beauty_manager, ffi.Bool)>>(
      'tx_beauty_manager_enable_sharpness_enhancement');
  late final _tx_beauty_manager_enable_sharpness_enhancement =
      _tx_beauty_manager_enable_sharpness_enhancementPtr
          .asFunction<int Function(tx_beauty_manager, bool)>();

  int tx_beauty_manager_set_ruddy_level(
    tx_beauty_manager instance,
    int level,
  ) {
    return _tx_beauty_manager_set_ruddy_level(
      instance,
      level,
    );
  }

  late final _tx_beauty_manager_set_ruddy_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(tx_beauty_manager, ffi.Int)>>(
          'tx_beauty_manager_set_ruddy_level');
  late final _tx_beauty_manager_set_ruddy_level =
      _tx_beauty_manager_set_ruddy_levelPtr
          .asFunction<int Function(tx_beauty_manager, int)>();
}
