name: tencent_trtc_cloud
description: With TRTC, you can quickly develop cost-effective, low-latency, and high-quality interactive audio/video services.
version: 2.9.5
repository: https://github.com/LiteAVSDK/TRTC_Flutter
homepage: https://trtc.io/
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2
  json_annotation: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.2
flutter:
  plugin:
    platforms:
      android:
        package: com.tencent.trtcplugin
        pluginClass: TRTCCloudPlugin
      ios:
        pluginClass: TencentTRTCCloud
      windows:
        pluginClass: TencentTrtcCloudPlugin
      macos:
        pluginClass: TencentTRTCCloud
      web:
        fileName: web/trtc_cloud_web.dart
        pluginClass: TencentTRTCCloudWeb
