
public enum ListenerType{
	case onError
	case onWarning
	case onEnterRoom
	case onExitRoom
	case onSwitchRole
	case onConnectOtherRoom
	case onDisConnectOtherRoom
	case onSwitchRoom
	case onRemoteUserEnterRoom
	case onRemoteUserLeaveRoom
	case onUserVideoAvailable
	case onUserSubStreamAvailable
	case onUserAudioAvailable
	case onFirstVideoFrame
	case onFirstAudioFrame
	case onSendFirstLocalAudioFrame
	case onSendFirstLocalVideoFrame
    case onSystemAudioLoopbackError
	case onNetworkQuality
	case onStatistics
	case onConnectionLost
	case onTryToReconnect
	case onConnectionRecovery
	case onSpeedTest
    case onSpeedTestResult
	case onCameraDidReady
	case onMicDidReady
    case onDeviceChange
    case onTestMicVolume
    case onTestSpeakerVolume
	case onAudioRouteChanged
	case onUserVoiceVolume
	case onRecvCustomCmdMsg
	case onMissCustomCmdMsg
	case onRecvSEIMsg
	case onStartPublishing
	case onStopPublishing
    case onStartPublishCDNStream
    case onStopPublishCDNStream
	case onSetMixTranscodingConfig
	case onAudioEffectFinished
	case onScreenCaptureStarted
	case onScreenCapturePaused
	case onScreenCaptureResumed
	case onScreenCaptureStoped
    case onSnapshotComplete
	case onMusicObserverStart
	case onMusicObserverPlayProgress
	case onMusicObserverComplete
}
